"""adding the name column

Revision ID: 363268133a3b
Revises: 98f3f9aa6582
Create Date: 2022-07-28 12:24:41.035046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363268133a3b'
down_revision = '98f3f9aa6582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
